packages:
  - 'packages/*'
  - '!**/test/**'
overrides:
  electron: 43.2.0
allowBuilds:
  '@nestjs/core': true
  electron: true
  electron-winstaller: true
  esbuild: true
  simple-git-hooks: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - check-package-exists
  - electron
  - electron-winstaller
  - esbuild
  - mono-release
  - simple-git-hooks

shellEmulator: true
trustPolicy: off

minimumReleaseAgeExclude:
  - lint-staged@17.0.6
