name: Publish Package

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'Doubleshotjs/doubleshot'
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install deps
        run: pnpm i --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish package
        run: pnpm run ci-publish ${{ github.ref_name }}
